### ISSUE TITLE
Links to DARPA dataset are broken

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/ml-ids#7]
It looks like MIT Lincoln Laboratory recently updated their website:

https://www.ll.mit.edu/r-d/datasets/1999-darpa-intrusion-detection-evaluation-data-set

Unforunately, the URLS to download the tcpdump files are broken. For example, from [week 1](ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week1/index.html): 

ftp://ftp.ll.mit.edu/ideval/data/1999/training/week1/monday/outside.tcpdump.gz

returns FTP errors.

**Comment by lukehsiao** [comment]
According to the MITLL webmaster, they are in process of fixing the links.

Week 1:
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week1/monday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week1/monday/inside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week1/tuesday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week1/tuesday/inside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week1/wednesday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week1/wednesday/inside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week1/thursday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week1/thursday/inside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week1/friday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week1/friday/inside.tcpdump.gz

Week 2:
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week2/monday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week2/monday/inside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week2/tuesday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week2/tuesday/inside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week2/wednesday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week2/wednesday/inside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week2/thursday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week2/thursday/inside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week2/friday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week2/friday/inside.tcpdump.gz

Week 3:
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week3/monday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week3/monday/inside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week3/tuesday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week3/tuesday/inside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week3/wednesday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week3/wednesday/inside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week3/thursday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week3/thursday/inside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week3/friday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/training/week3/friday/inside.tcpdump.gz

 

Week 4:
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/testing/week4/monday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/testing/week4/monday/inside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/testing/week4/tuesday/outside.tcpdump.gz

-Tuesday Inside Data- See Errata below
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/testing/week4/wednesday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/testing/week4/wednesday/inside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/testing/week4/thursday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/testing/week4/thursday/inside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/testing/week4/friday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/testing/week4/friday/inside.tcpdump.gz

Errata.

Tuesday, March 30
Hume's Event logs were collected recently from a backup tape taken after the 4-2 run.  There may be Events dated Apr. 24th -- These and any other events not between the specified range of the 4-2 run should be ignored.

There is no "inside.tcpdump" file for this day.   Systems will not be held responsible for attacks for which significant evidence of the attack would have been in this file.

Week 5:
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/testing/week5/monday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/testing/week5/monday/inside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/testing/week5/tuesday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/testing/week5/tuesday/inside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/testing/week5/wednesday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/testing/week5/wednesday/inside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/testing/week5/thursday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/testing/week5/thursday/inside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/testing/week5/friday/outside.tcpdump.gz
ftp://ftp.ll.mit.edu/outgoing/darpa/data/1999/testing/week5/friday/inside.tcpdump.gz

---

We will likely need to update our download_data.sh to match these URLs.

**Comment by raminfouladi** [comment]
hi @lukehsiao , do you have darpa data in backup, the links are still broken!

**Comment by lukehsiao** [comment]
@raminfouladi, the ftp links in [my comment above](https://github.com/lukehsiao/ml-ids/issues/7#issuecomment-404562382) work fine for me.

**Comment by raminfouladi** [comment]
![image](https://user-images.githubusercontent.com/25265522/44596703-e401dc80-a7d5-11e8-84e5-e1abf1a08121.jpg)
Thx for ur prompt reply @lukehsiao When I use your sh file I get the error ‘unexpected end of file ‘ each file

**Comment by lukehsiao** [comment]
@raminfouladi You'll have to do some more debugging since the URLs above are working. The downloads work on my machine and on Travis-CI. Feel free to submit a PR if you are able to identify your issue and resolve it.

You may want to try using `curl` instead of `wget`.

**Comment by raminfouladi** [comment]
@lukehsiao wget fttp gets time out problem and cannot connect to ftp://ftp.ll.mit.edu, That is why I get the error. should i provide user name and pass to connect to the server.

**Comment by lukehsiao** [comment]
No, it's a public ftp server, no username or pass needed. You can just download the files yourself through your browser too.

**Comment by raminfouladi** [comment]
Same problem when using the browser !

**Comment by sibanez12** [comment]
I can confirm the links above work for me as well.

**Comment by zemrearslan** [comment]
Did you manage to download the data set? Your links seem to be broken again. :(  @lukehsiao

**Comment by lukehsiao** [comment]
The links are still working. I suspect it their FTP server may be restricting it by location. Are you outside of the US?

https://www.ll.mit.edu/r-d/datasets/1999-darpa-intrusion-detection-evaluation-data-set

**Comment by zemrearslan** [comment]
You might be right, unfortunately im outside of the states.

**Comment by lukehsiao** [comment]
> You might be right, unfortunately im outside of the states.

They used to be served over HTTP rather than FTP. You could reach out to the [webmaster](https://www.ll.mit.edu/contact-us) there to see if they can help you.

**Comment by zemrearslan** [comment]
> > You might be right, unfortunately im outside of the states.
> 
> They used to be served over HTTP rather than FTP. You could reach out to the [webmaster](https://www.ll.mit.edu/contact-us) there to see if they can help you.

Actually, I already sent an email to the webmaster. Haven't got an answer yet. Thank you very much for your interest :)

**Comment by kumagallium** [comment]
I also got the same error because I am outside of the US. So, I borrowed an AWS server in US region and solved it by downloading on the server.

**Comment by mengxiaoking** [comment]
how to use these links? please help me. thank you very much

**Comment by mengxiaoking** [comment]
how to use these links? please help me. thank you very much @lukehsiao

**Comment by RyuAsuka** [comment]
The links are not repaired until now...

**Comment by lukehsiao** [comment]
It does not appear that the MIT Lincoln Lab will be moving away from their FTP links. All of the FTP links work, though they appear to be restricted to users in the United States. I do not have mirrors for the dataset, and will not be hosting any mirrors.

Also note that there are numerious issues with this simulated dataset, and the ML community recommends **not** using the KDD or DARPA datasets [[1]], [[2]], [[3]], [[4]], [[5]].

Locking this issue since it is resolved. Please reach out to the MIT Lincoln Lab webmasters for questions about their geographic restrictions.

[1]: https://www.kdnuggets.com/news/2007/n18/4i.html
[2]: https://ieeexplore.ieee.org/abstract/document/6169141/
[3]: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.94.674&rep=rep1&type=pdf
[4]: https://link.springer.com/chapter/10.1007/978-3-540-45248-5_13
[5]: https://dl.acm.org/citation.cfm?id=382923
