### ISSUE TITLE
How to convert tcmdump file into npy?

### ISSUE THREAD

**Issue by GaoXiJieJie** [lukehsiao/ml-ids#8]
Hello, It made me wonder how did you convert the downloaded tcpdump file to npy form? Look forward to your reply!

**Comment by lukehsiao** [comment]
https://github.com/lukehsiao/ml-ids/blob/master/utils/pcap_parser.py

**Comment by GaoXiJieJie** [comment]
Oh, I'm sorry that I didn't see the file before. Thanks for your reply.
